# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-05 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_auto_20170831_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='TinyTrackerReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('value', models.TextField()),
                ('state', models.TextField()),
            ],
        ),
    ]
